spring:
  application:
    name: user-service

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  data:
    redis:
      enabled: ${REDIS_ENABLED:true}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:}  # optional

  security:
    jwt:
      secret: ${JWT_SECRET}
      access-expiration: ${JWT_ACCESS_EXPIRATION:900000}      # 15 minutes default
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}  # 24 hours default
    service-whitelist:
      enabled: true
      hosts: [ "127.0.0.1" ]

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8083

grpc:
  server:
    port: 7093
    security:
      enabled: false
  client:
    security-service:
      address: static://localhost:7080
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-time: 30s
      keep-alive-timeout: 5s
    client-custom:
      timeout-seconds: 30
      retry:
        max-attempts: 3
        delay-milliseconds: 1000

kafka:
  enabled: true
  consumer-enabled: false
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  topics:
    user: ${KAFKA_USER_TOPIC:user}
  transactional-outbox:
    enabled: true

app:
  security-service:
    url: http://localhost:8080

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.grpc_utils: DEBUG