spring:
  application:
    name: websocket-hub-service

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  security:
    jwt:
      secret: ${JWT_SECRET}
      access-expiration: ${JWT_ACCESS_EXPIRATION}
      refresh-expiration: ${JWT_REFRESH_EXPIRATION}

  data:
    redis:
      enabled: ${REDIS_ENABLED:true}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:}  # optional

server:
  port: 8081
  forward-headers-strategy: framework

server-url: ${SERVER_URL:http://localhost:8081}

grpc:
  client:
    user-service:
      address: ${GRPC_USER_SERVICE_ADDRESS:static://localhost:7093}
      negotiation-type: plaintext
      keep-alive-time: 30s
      keep-alive-timeout: 5s
    bank-service:
      address: ${GRPC_BANK_SERVICE_ADDRESS:static://localhost:7094}
      negotiation-type: plaintext
      keep-alive-time: 30s
      keep-alive-timeout: 5s
  client-custom:
    timeout-seconds: 30
    retry:
      max-attempts: 3
      delay-milliseconds: 1000

app:
  game-service:
    url: ${GAME_SERVICE_URL:http://localhost:8082}

cron:
  room-cleanup:
    cleanup-rooms: ${CRON_CLEANUP_ROOMS:0 0/5 * * * *}
    cleanup-pending-delete-rooms: ${CRON_CLEANUP_PENDING_DELETE_ROOMS:0 2/5 * * * *}
    finished-kick-timeout-minutes: 2
    waiting-stale-timeout-minutes: 30
    tic-tac-toe-in-progress-timeout-minutes: 20
    durak-in-progress-timeout-minutes: 60
    de-coder-in-progress-timeout-minutes: 60

kafka:
  enabled: ${KAFKA_ENABLED:true}
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  producer-config:
    "[acks]": "1"
  topics:
    room-lifecycle: ${KAFKA_ROOM_LIFECYCLE_TOPIC:room-lifecycle}

logging:
  level:
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB:INFO}
    org.springframework.web.websocket: ${LOG_LEVEL_WEBSOCKET:INFO}
    com.grpc_utils: ${LOG_LEVEL_GRPC:INFO}

springdoc:
  preLoadingEnabled: true
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
    path: /v3/api-docs
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    path: /swagger-ui.html
