spring:
  application:
    name: security-service

  config:
    import: optional:file:.env[.properties]

  autoconfigure:
    exclude:
      - net.devh.boot.grpc.server.autoconfigure.GrpcServerSecurityAutoConfiguration

  datasource:
    url: jdbc:postgresql://${SECURITY_POSTGRES_HOST:localhost}:${SECURITY_POSTGRES_PORT:5432}/${SECURITY_POSTGRES_DB:diploma}?currentSchema=${SECURITY_DB_DEFAULT_SCHEMA:security_service}
    username: ${SECURITY_POSTGRES_USERNAME:postgres}
    password: ${SECURITY_POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: security_service
    liquibase-schema: security_service

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: security_service
        jdbc:
          time_zone: UTC

  data:
    redis:
      enabled: ${REDIS_ENABLED:true}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:}  # optional

  security:
    jwt:
      secret: ${JWT_SECRET}
      access-expiration: ${JWT_ACCESS_EXPIRATION:600000}      # 10 minutes default
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}  # 24 hours default
    service-whitelist:
      enabled: ${SERVICE_WHITELIST_ENABLED:true}
      hosts: [ "127.0.0.1" ]

grpc:
  server:
    port: 7090
    security:
      enabled: false
  client:
    user-service:
      address: ${GRPC_USER_SERVICE_ADDRESS:static://localhost:7093}
      negotiation-type: plaintext
      keep-alive-time: 30s
      keep-alive-timeout: 5s
  client-custom:
    timeout-seconds: 30
    retry:
      max-attempts: 3
      delay-milliseconds: 1000

server:
  port: 8080
  forward-headers-strategy: framework

server-url: ${SERVER_URL:http://localhost:8080}

kafka:
  enabled: true
  consumer-enabled: true
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  consumer-config:
    "[group.id]": security-service-user-sync
    "[auto.offset.reset]": earliest
  topics:
    user: ${KAFKA_USER_TOPIC:user}

ws-ticket:
  ttl-seconds: ${WS_TICKET_TTL_SECONDS:30}

logging:
  level:
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB:INFO}
    org.springframework.security: ${LOG_LEVEL_SPRING_SECURITY:INFO}
    com.grpc_utils: ${LOG_LEVEL_GRPC:INFO}

springdoc:
  preLoadingEnabled: true
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
    path: /v3/api-docs
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    path: /swagger-ui.html
    operationsSorter: alpha
