spring:
  application:
    name: bank-service

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${BANK_POSTGRES_HOST:localhost}:${BANK_POSTGRES_PORT:5432}/${BANK_POSTGRES_DB:diploma}?currentSchema=${BANK_DB_DEFAULT_SCHEMA:bank_service}
    username: ${BANK_POSTGRES_USERNAME:postgres}
    password: ${BANK_POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: bank_service
    liquibase-schema: bank_service

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: bank_service
        jdbc:
          time_zone: UTC

  data:
    redis:
      enabled: ${REDIS_ENABLED:true}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:}

  security:
    jwt:
      secret: ${JWT_SECRET}
      access-expiration: ${JWT_ACCESS_EXPIRATION:600000}      # 10 minutes default
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}  # 24 hours default
      public-paths:
        - /v3/api-docs/**
        - /swagger-ui.html
        - /swagger-ui/**
        - /webjars/**
    service-whitelist:
      enabled: ${SERVICE_WHITELIST_ENABLED:true}
      hosts: [ "127.0.0.1" ]

server:
  port: 8084
  forward-headers-strategy: framework

server-url: ${SERVER_URL:http://localhost:8084}

grpc:
  server:
    port: 7094
    security:
      enabled: false
  client:
    user-service:
      address: ${GRPC_USER_SERVICE_ADDRESS:static://localhost:7093}
      negotiation-type: plaintext
      keep-alive-time: 30s
      keep-alive-timeout: 5s
  client-custom:
    timeout-seconds: 30
    retry:
      max-attempts: 3
      delay-milliseconds: 1000

kafka:
  enabled: true
  consumer-enabled: true
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  consumer-config:
    "[group.id]": bank-service-update-subscription
    "[auto.offset.reset]": earliest
  topics:
    update-subscription: ${KAFKA_UPDATE_SUBSCRIPTION_TOPIC:update-subscription}

cron:
  create-transaction-summaries: ${CRON_CREATE_TRANSACTION_SUMMARIES:0 0 3 1 * *}

  scheduling:
    transaction-summary:
      initial-delay: 10000
      fixed-rate: P30D # every month default

logging:
  level:
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB:INFO}
    org.springframework.security: ${LOG_LEVEL_SPRING_SECURITY:INFO}
    com.grpc_utils: ${LOG_LEVEL_GRPC:INFO}

springdoc:
  preLoadingEnabled: true
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
    path: /v3/api-docs
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    path: /swagger-ui.html
