spring:
  application:
    name: bank-service

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${BANK_POSTGRES_HOST}:${BANK_POSTGRES_PORT}/${BANK_POSTGRES_DB}
    username: ${BANK_POSTGRES_USERNAME}
    password: ${BANK_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 15
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

  data:
    redis:
      enabled: ${REDIS_ENABLED:true}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:}

  security:
    jwt:
      secret: ${JWT_SECRET}
      access-expiration: ${JWT_ACCESS_EXPIRATION:900000}      # 15 minutes default
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}  # 24 hours default
    service-whitelist:
      enabled: true
      hosts: [ "127.0.0.1" ]

server:
  port: 8084

app:
  user-service:
    url: http://localhost:8083

logging:
  level:
    org.springframework.web: DEBUG
