spring:
  application:
    name: game-service

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${GAME_POSTGRES_HOST:localhost}:${GAME_POSTGRES_PORT:5432}/${GAME_POSTGRES_DB:diploma}
    username: ${GAME_POSTGRES_USERNAME:postgres}
    password: ${GAME_POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8082

logging:
  level:
    org.springframework.web: DEBUG
