plugins {
    id 'java-library'
    id 'org.springframework.boot' version '3.5.14'
    id 'io.spring.dependency-management'
    id 'maven-publish'
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}

def springDoc = '2.8.17'

dependencies {
    implementation 'org.springframework:spring-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    compileOnly 'org.springframework.boot:spring-boot-starter-web'

    compileOnly "org.springdoc:springdoc-openapi-starter-common:${springDoc}"

    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}
